name: smart_farming
description: "Smart farming aplikasi untuk monitoring dan kontrol pertanian secara otomatis menggunakan IoT"
publish_to: 'none'

version: 1.0.5

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  
  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  
  # Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.2
  firebase_messaging: ^16.1.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Network
  http: ^1.6.0
  
  # Notifications
  flutter_local_notifications: ^19.5.0
  permission_handler: ^12.0.1
  
  # Utils
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

# âœ… Launcher Icons Configuration (HARUS DI LUAR flutter:)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png
  min_sdk_android: 21
  remove_alpha_ios: true
  # adaptive_icon_background: "#FFFFFF"
  # adaptive_icon_foreground: assets/icon/app_icon_foreground.png

flutter:
  uses-material-design: true

  assets:
    - assets/dev/
    # - assets/images/
    # - assets/icon/

  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
